<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NormalizedQuery" xmlns:tns="http://www.example.org/NormalizedQuery" elementFormDefault="qualified">

    <element name="NormalizePolicyQuery" type="tns:NormalizePolicyQueryType"></element>

    <complexType name="NormalizePolicyQueryType">
    	<sequence>
    		<element name="question" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="topK" type="integer" minOccurs="0"
    			maxOccurs="1">
    		</element>
            <element name="minScore" type="decimal" minOccurs="0" maxOccurs="1"></element>
            <element name="documentTypes" type="string" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="category" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>
</schema>