-- =============================================================================
-- RetailCo Beauty DB — Patch 002
-- Applied: 2026-05-13
-- =============================================================================
-- Widens loyalty_offers.offer_id from VARCHAR(30) to VARCHAR(36) to accommodate
-- UUID strings (36 characters including hyphens) generated by gen_random_uuid().
--
-- Run this if Patch 001 was already applied but CreateLoyaltyOffer still fails
-- with: "value too long for type character varying(30)"
--
-- Usage:
--   psql -U postgres -d beauty_db -f beauty-schema-patch-002.sql
-- =============================================================================

ALTER TABLE loyalty_offers
  ALTER COLUMN offer_id TYPE VARCHAR(36);
