<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778454883606" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778454883606">
  <complexType name="GetToolsResponseElementType">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" name="tools">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="name" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="description" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="safety" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="inputSchema">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="type" type="string"/>
                  <element maxOccurs="unbounded" minOccurs="0" name="required" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="properties">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="sku">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="type" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="description" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                      </sequence>
                    </complexType>
                  </element>
                </sequence>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="GetToolsResponseElement" type="tns:GetToolsResponseElementType"/>
</schema>
