<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778455097850" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778455097850">
  <complexType name="PostToolsInventoryResponseElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="productName" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="storeId" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="quantity" type="integer"/>
      <element maxOccurs="1" minOccurs="0" name="status" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="aisle" type="string"/>
    </sequence>
  </complexType>
  <element name="PostToolsInventoryResponseElement" type="tns:PostToolsInventoryResponseElementType"/>
</schema>
