<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ProductInventorySchema" xmlns:tns="http://www.example.org/ProductInventorySchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="ProductInventoryList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ProductInventory" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
            	<xs:element type="xs:string" name="sku" />
            	<xs:element type="xs:string" name="name" />
            	<xs:element type="xs:string" name="brand" />
            	<xs:element type="xs:string" name="category" />
            	<xs:element type="decimal" name="price" />
            	<xs:element type="xs:string" name="description" />
                            <element name="inventoryStatus" type="string" minOccurs="0" maxOccurs="1"></element>
                            <xs:element name="InventoryList" minOccurs="0"
            		maxOccurs="unbounded">
            		<xs:complexType>
            			<xs:sequence>
            				<element name="sku" type="string"
            					minOccurs="0" maxOccurs="1">
            				</element>
                                        <element name="name" type="string" minOccurs="0" maxOccurs="1"></element>
                                        <element name="storeId" type="string"
            					minOccurs="0" maxOccurs="1">
            				</element>
            				<element name="quantity" type="integer"
            					minOccurs="0" maxOccurs="1">
            				</element>
            				<element name="aisle" type="string"
            					minOccurs="0" maxOccurs="1">
            				</element>
            				<element name="status" type="string"
            					minOccurs="0" maxOccurs="1">
            				</element>
            			</xs:sequence>
            		</xs:complexType>
            	</xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</schema>