package com.retail.agent;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RetailAgentPlanner {

    private static final Pattern SKU_PATTERN =
            Pattern.compile("[A-Z]{3,5}-[A-Z0-9]{3,8}-[0-9]{3}", Pattern.CASE_INSENSITIVE);

    private static final Pattern ORDER_ID_PATTERN =
            Pattern.compile("ORD-[0-9]{4,}", Pattern.CASE_INSENSITIVE);

    private final ObjectMapper mapper = new ObjectMapper();

    public String plan(String question, String customerId, String storeId, String memoryJson) throws Exception {
        String safeQuestion = question == null ? "" : question.trim();
        String safeCustomerId = defaultString(customerId, "CUST-001");
        String safeStoreId = defaultString(storeId, "SFO-001");

        Memory memory = parseMemory(memoryJson);
        String planningText = memory.enabled
                ? memory.summary + "\nCurrent question: " + safeQuestion
                : safeQuestion;

        String sku = firstMatch(SKU_PATTERN, planningText);
        String orderId = firstMatch(ORDER_ID_PATTERN, planningText);
        String category = inferCategory(planningText);
        int maxPrice = maxPrice(planningText);
        String intent = detectIntent(safeQuestion, planningText);

        ObjectNode root = mapper.createObjectNode();
        root.put("intent", intent);

        ObjectNode context = root.putObject("context");
        context.put("customerId", safeCustomerId);
        context.put("storeId", safeStoreId);

        ObjectNode entities = root.putObject("entities");
        entities.put("sku", defaultString(sku, ""));
        entities.put("orderId", defaultString(orderId, ""));
        entities.put("category", defaultString(category, ""));
        entities.put("maxPrice", maxPrice);
        entities.put("wantsApprovalAction", wantsApprovalAction(safeQuestion));

        root.put("requiresRetrieval", true);

        ArrayNode plan = root.putArray("plan");
        addPlanSteps(plan, intent, safeQuestion, sku, orderId, category);

        ArrayNode actions = root.putArray("actions");
        addActions(actions, intent, safeQuestion, safeCustomerId, safeStoreId, sku, orderId, category);

        root.put("plannerNotes", "Generated by BW6 deterministic Java planner.");

        ObjectNode memoryNode = root.putObject("memory");
        memoryNode.put("enabled", memory.enabled);
        memoryNode.put("messageCount", memory.messageCount);
        memoryNode.put("includedMessages", memory.includedMessages);

        return mapper.writeValueAsString(root);
    }

    private void addPlanSteps(ArrayNode plan, String intent, String question, String sku, String orderId, String category) {
        plan.add("Understand the customer goal and extract retail entities.");
        plan.add("Retrieve relevant product, policy, FAQ, and promotion context.");

        if (notBlank(orderId)) {
            plan.add("Look up order " + orderId + ".");
        }

        if (notBlank(sku)) {
            plan.add("Look up product " + sku + ".");
        }

        if ("return_flow".equals(intent)) {
            plan.add("Check return eligibility using order data and policy context.");
        }

        if ("inventory_lookup".equals(intent) || "reserve_inventory".equals(intent)) {
            plan.add("Check live store inventory.");
        }

        if ("recommend".equals(intent) || "recommend_and_promote".equals(intent)) {
            plan.add("Find suitable " + (notBlank(category) ? category : "retail") + " products that match the request.");
            plan.add("Check applicable loyalty promotions.");
        }

        if ("reserve_inventory".equals(intent)) {
            plan.add("Pause for approval before reserving inventory.");
        }

        if ("recommend_and_promote".equals(intent)) {
            plan.add("Pause for approval before applying a promotion.");
        }

        if (wantsReturnAuthorizationFromQuestion(question)) {
            plan.add("Pause for approval before creating a return authorization.");
        }

        plan.add("Synthesize the final answer with citations and observations.");
    }

    private void addActions(
            ArrayNode actions,
            String intent,
            String question,
            String customerId,
            String storeId,
            String sku,
            String orderId,
            String category
    ) {
        if (notBlank(sku)) {
            actions.add(toolAction(
                    "get_product",
                    sku,
                    "",
                    storeId,
                    customerId,
                    "",
                    "",
                    false,
                    "Product SKU was provided."
            ));
        }

        if (notBlank(orderId)) {
            actions.add(toolAction(
                    "lookup_order",
                    "",
                    orderId,
                    storeId,
                    customerId,
                    "",
                    "",
                    false,
                    "Order ID was provided."
            ));
        }

        if ("return_flow".equals(intent) && notBlank(orderId)) {
            actions.add(toolAction(
                    "check_return_eligibility",
                    "",
                    orderId,
                    storeId,
                    customerId,
                    "",
                    "",
                    false,
                    "Return intent requires eligibility check."
            ));
        }

        if (("inventory_lookup".equals(intent) || "reserve_inventory".equals(intent)) && notBlank(sku)) {
            actions.add(toolAction(
                    "check_inventory",
                    sku,
                    "",
                    storeId,
                    customerId,
                    "",
                    "",
                    false,
                    "Inventory status is needed."
            ));
        }

        if ("recommend_and_promote".equals(intent)) {
            actions.add(toolAction(
                    "find_promotions",
                    defaultString(sku, ""),
                    "",
                    storeId,
                    customerId,
                    defaultString(category, ""),
                    "",
                    false,
                    "Promotion context is required before applying a promotion."
            ));
        } else if ("recommend".equals(intent) && notBlank(category)) {
            actions.add(toolAction(
                    "find_promotions",
                    "",
                    "",
                    storeId,
                    customerId,
                    category,
                    "",
                    false,
                    "Promotion context may affect the recommendation."
            ));
        }

        if ("reserve_inventory".equals(intent) && notBlank(sku)) {
            actions.add(toolAction(
                    "reserve_inventory",
                    sku,
                    "",
                    storeId,
                    customerId,
                    "",
                    "",
                    true,
                    "Reservation changes store inventory state."
            ));
        }

        if ("recommend_and_promote".equals(intent) && wantsPromotionApplicationFromQuestion(question)) {
            actions.add(toolAction(
                    "apply_promotion",
                    defaultString(sku, ""),
                    "",
                    storeId,
                    customerId,
                    defaultString(category, ""),
                    "",
                    true,
                    "Applying a promotion changes customer cart state."
            ));
        }

        if ("return_flow".equals(intent) && notBlank(orderId) && wantsReturnAuthorizationFromQuestion(question)) {
            actions.add(toolAction(
                    "create_return_authorization",
                    "",
                    orderId,
                    storeId,
                    customerId,
                    "",
                    "",
                    true,
                    "Creating a return authorization changes order state."
            ));
        }
    }

    private ObjectNode toolAction(
            String toolName,
            String sku,
            String orderId,
            String storeId,
            String customerId,
            String category,
            String promotionId,
            boolean requiresApproval,
            String rationale
    ) {
        ObjectNode action = mapper.createObjectNode();
        action.put("toolName", toolName);
        action.put("sku", defaultString(sku, ""));
        action.put("orderId", defaultString(orderId, ""));
        action.put("storeId", defaultString(storeId, ""));
        action.put("customerId", defaultString(customerId, ""));
        action.put("category", defaultString(category, ""));
        action.put("promotionId", defaultString(promotionId, ""));
        action.put("requiresApproval", requiresApproval);
        action.put("rationale", rationale);
        return action;
    }

    private String detectIntent(String currentQuestion, String planningText) {
        String current = currentQuestion == null ? "" : currentQuestion.toLowerCase();
        String planned = planningText == null ? "" : planningText.toLowerCase();
        boolean hasOrderId = firstMatch(ORDER_ID_PATTERN, planningText).length() > 0;

        if (wantsReturnAuthorizationFromQuestion(currentQuestion)) {
            return "return_flow";
        }

        if (isReturnPolicyQuestion(current) && !hasOrderId) {
            return "knowledge_answer";
        }

        if (current.contains("reserve") || current.contains("hold")) {
            return "reserve_inventory";
        }

        if (wantsPromotionApplicationFromQuestion(currentQuestion)) {
            return "recommend_and_promote";
        }

        if ((current.contains("return") || current.contains("refund")) && hasOrderId) {
            return "return_flow";
        }

        if (current.contains("recommend") || current.contains("similar") || current.contains("find") || current.contains("under")) {
            return "recommend";
        }

        if (planned.contains("stock") || planned.contains("inventory") || planned.contains("available")) {
            return "inventory_lookup";
        }

        return "knowledge_answer";
    }

    private boolean isReturnPolicyQuestion(String lowerQuestion) {
        if (lowerQuestion == null) return false;

        return lowerQuestion.contains("return policy")
                || lowerQuestion.contains("returns policy")
                || lowerQuestion.contains("return window")
                || lowerQuestion.contains("return rules")
                || lowerQuestion.contains("return period")
                || lowerQuestion.contains("what is")
                || lowerQuestion.contains("what are")
                || lowerQuestion.contains("how many days");
    }

    private String inferCategory(String text) {
        String lower = text == null ? "" : text.toLowerCase();

        if (lower.contains("shoe") || lower.contains("running") || lower.contains("footwear")) return "Footwear";
        if (lower.contains("jacket") || lower.contains("outerwear") || lower.contains("fleece")) return "Outerwear";
        if (lower.contains("bag") || lower.contains("backpack")) return "Bags";
        if (lower.contains("watch") || lower.contains("earbud") || lower.contains("electronics")) return "Electronics";
        if (lower.contains("bottle")) return "Accessories";
        if (lower.contains("mat") || lower.contains("yoga")) return "Fitness";

        return "";
    }

    private int maxPrice(String text) {
        if (text == null) return 0;

        Matcher matcher = Pattern.compile("under\\s+\\$?([0-9]+)", Pattern.CASE_INSENSITIVE).matcher(text);
        return matcher.find() ? Integer.parseInt(matcher.group(1)) : 0;
    }

    private boolean wantsApprovalAction(String question) {
        String lower = question == null ? "" : question.toLowerCase();

        return lower.contains("reserve")
                || lower.contains("hold")
                || wantsReturnAuthorizationFromQuestion(question)
                || wantsPromotionApplicationFromQuestion(question);
    }

    private boolean wantsReturnAuthorizationFromQuestion(String question) {
        String lower = question == null ? "" : question.toLowerCase();

        return lower.matches(".*create\\s+(a\\s+)?return.*")
                || lower.contains("return authorization");
    }

    private boolean wantsPromotionApplicationFromQuestion(String question) {
        String lower = question == null ? "" : question.toLowerCase();

        boolean hasApplyVerb =
                lower.contains("apply")
                        || lower.contains("add")
                        || lower.contains("use")
                        || lower.contains("redeem");

        boolean hasPromotionTerm =
                lower.contains("promotion")
                        || lower.contains("promo")
                        || lower.contains("discount")
                        || lower.contains("coupon");

        return hasApplyVerb && hasPromotionTerm;
    }

    private String firstMatch(Pattern pattern, String text) {
        if (text == null) return "";

        Matcher matcher = pattern.matcher(text);
        return matcher.find() ? matcher.group(0).toUpperCase() : "";
    }

    private Memory parseMemory(String memoryJson) {
        Memory memory = new Memory();

        if (memoryJson == null || memoryJson.trim().isEmpty()) {
            return memory;
        }

        try {
            JsonNode root = mapper.readTree(memoryJson);
            memory.enabled = root.path("enabled").asBoolean(false);
            memory.messageCount = root.path("messageCount").asInt(0);
            memory.includedMessages = root.path("includedMessages").asInt(0);
            memory.summary = root.path("summary").asText("");
        } catch (Exception ignored) {
            memory.enabled = false;
            memory.summary = "";
        }

        return memory;
    }

    private String defaultString(String value, String fallback) {
        return value == null || value.isEmpty() ? fallback : value;
    }

    private boolean notBlank(String value) {
        return value != null && !value.trim().isEmpty();
    }

    private static class Memory {
        boolean enabled = false;
        int messageCount = 0;
        int includedMessages = 0;
        String summary = "";
    }
}
