<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778560670802" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778560670802">
  <complexType name="AgentResponseSchemaElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="intent" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="entities">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="orderId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="category" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="maxPrice" type="integer"/>
            <element maxOccurs="1" minOccurs="0" name="wantsApprovalAction" type="boolean"/>
          </sequence>
        </complexType>
      </element>
      <element maxOccurs="unbounded" minOccurs="0" name="plan" type="string"/>
      <element maxOccurs="unbounded" minOccurs="0" name="actions">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="toolName" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="storeId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="customerId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="requiresApproval" type="boolean"/>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="AgentResponseSchemaElement" type="tns:AgentResponseSchemaElementType"/>
</schema>
