<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778966201686" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778966201686">
    
    
  <element name="EnrichedPendingApproval" type="tns:EnrichedPendingApprovalType"/>
      
  <element name="Operations" type="tns:OperationsType"/>
      
  <complexType name="OperationsType">
        	
    <sequence>
          		
      <element maxOccurs="1" minOccurs="0" name="provider" type="string"/>
          		
      <element maxOccurs="1" minOccurs="0" name="approvalId" type="string"/>
          		
      <element maxOccurs="1" minOccurs="0" name="status" type="string"/>
          	
    </sequence>
        
  </complexType>
  

    <complexType name="EnrichedPendingApprovalType">
    	<sequence>
    		<element maxOccurs="1" minOccurs="0" name="approvalId"
    			type="string" />
    		<element maxOccurs="1" minOccurs="0" name="toolName"
    			type="string" />
    		<element maxOccurs="1" minOccurs="0" name="arguments">
    			<complexType>
    				<sequence>
    					<element maxOccurs="1" minOccurs="0" name="sku"
    						type="string" />
    					<element maxOccurs="1" minOccurs="0"
    						name="storeId" type="string" />
    					<element maxOccurs="1" minOccurs="0"
    						name="customerId" type="string" />
    					<element name="orderId" type="string" minOccurs="0" maxOccurs="1"></element>
    					<element name="promotionId" type="string" minOccurs="0" maxOccurs="1"></element>
    				</sequence>
    			</complexType>
    		</element>
    		<element name="summary" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="status" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="root">
    	<complexType>
    		<sequence>
    			<element ref="tns:EnrichedPendingApproval" minOccurs="0" maxOccurs="1"></element>
    			<element ref="tns:Operations" minOccurs="0" maxOccurs="1"></element>
    		</sequence>
    	</complexType></element>
</schema>
