<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778562475043" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778562475043">
  <complexType name="PlannerSchemaElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="intent" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="context">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="customerId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="storeId" type="string"/>
          </sequence>
        </complexType>
      </element>
      <element maxOccurs="1" minOccurs="0" name="entities">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="orderId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="category" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="maxPrice" type="integer"/>
            <element maxOccurs="1" minOccurs="0" name="wantsApprovalAction" type="boolean"/>
          </sequence>
        </complexType>
      </element>
      <element maxOccurs="1" minOccurs="0" name="requiresRetrieval" type="boolean"/>
      <element maxOccurs="unbounded" minOccurs="0" name="plan" type="string"/>
      <element maxOccurs="unbounded" minOccurs="0" name="actions">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="toolName" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="orderId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="storeId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="customerId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="category" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="promotionId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="requiresApproval" type="boolean"/>
            <element maxOccurs="1" minOccurs="0" name="rationale" type="string"/>
          </sequence>
        </complexType>
      </element>
      <element maxOccurs="1" minOccurs="0" name="plannerNotes" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="memory">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="enabled" type="boolean"/>
            <element maxOccurs="1" minOccurs="0" name="messageCount" type="integer"/>
            <element maxOccurs="1" minOccurs="0" name="includedMessages" type="integer"/>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="PlannerSchemaElement" type="tns:PlannerSchemaElementType"/>
</schema>
