<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="/T1778596217369Converted/JsonSchema" xmlns:tns="/T1778596217369Converted/JsonSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PostPromotionApplyRequestElement" type="tns:PostPromotionApplyRequestElement"/>
    <xs:complexType name="PostPromotionApplyRequestElement">
        <xs:sequence>
            <xs:element minOccurs="0" name="customerId" type="xs:string"/>
            <xs:element minOccurs="0" name="promotionId" type="xs:string"/>
            <xs:element minOccurs="0" name="sku" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="GetPromotionsResponseElement" type="tns:GetPromotionsResponseElement"/>
    <xs:complexType name="GetPromotionsResponseElement">
        <xs:sequence>
            <xs:element minOccurs="0" name="customerId" type="xs:string"/>
            <xs:element minOccurs="0" name="category" type="xs:string"/>
            <xs:element minOccurs="0" name="customerTier" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="promotions" type="tns:promotions"/>
            <xs:element minOccurs="0" name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="promotions" type="tns:promotions"/>
    <xs:complexType name="promotions">
        <xs:sequence>
            <xs:element minOccurs="0" name="id" type="xs:string"/>
            <xs:element minOccurs="0" name="name" type="xs:string"/>
            <xs:element minOccurs="0" name="discountPercent" type="xs:int"/>
            <xs:element minOccurs="0" name="expiresOn" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="exclusions" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="arguments" type="tns:arguments"/>
    <xs:complexType name="arguments">
        <xs:sequence>
            <xs:element minOccurs="0" name="customerId" type="xs:string"/>
            <xs:element minOccurs="0" name="promotionId" type="xs:string"/>
            <xs:element minOccurs="0" name="sku" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="PostPromotionApplyResponseElement" type="tns:PostPromotionApplyResponseElement"/>
    <xs:complexType name="PostPromotionApplyResponseElement">
        <xs:sequence>
            <xs:element minOccurs="0" name="approvalRequired" type="xs:boolean"/>
            <xs:element minOccurs="0" name="tool" type="xs:string"/>
            <xs:element minOccurs="0" name="arguments" type="tns:arguments"/>
            <xs:element minOccurs="0" name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
