<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778954894364" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778954894364">
  <complexType name="RouteSchemaElementType">
    <sequence>
    	<element maxOccurs="1" minOccurs="0" name="customerId"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="storeId"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="memory">
    		<complexType>
    			<sequence>
    				<element maxOccurs="1" minOccurs="0" name="enabled"
    					type="boolean" />
    				<element maxOccurs="1" minOccurs="0"
    					name="messageCount" type="integer" />
    				<element maxOccurs="1" minOccurs="0"
    					name="includedMessages" type="integer" />
    			</sequence>
    		</complexType>
    	</element>
    	<element maxOccurs="1" minOccurs="0" name="detectedSku"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="detectedOrderId"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="detectedCategory"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="intent"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="mode" type="string" />
    	<element maxOccurs="1" minOccurs="0" name="planner">
    		<complexType>
    			<sequence>
    				<element maxOccurs="1" minOccurs="0" name="provider"
    					type="string" />
    				<element maxOccurs="1" minOccurs="0" name="model"
    					type="string" />
    				<element maxOccurs="1" minOccurs="0" name="warning"
    					type="string" />
    			</sequence>
    		</complexType>
    	</element>
    	<element maxOccurs="1" minOccurs="0" name="toolTransport">
    		<complexType>
    			<sequence>
    				<element maxOccurs="1" minOccurs="0" name="provider"
    					type="string" />
    				<element name="transport" type="string"
    					minOccurs="0" maxOccurs="1">
    				</element>
    				<element name="gatewayUrl" type="string"
    					minOccurs="0" maxOccurs="1">
    				</element>
    				<element name="endpoints" minOccurs="0"
    					maxOccurs="1">
    					<complexType>
    						<sequence>
    							<element name="inventory" type="string"
    								minOccurs="0" maxOccurs="1">
    							</element>
    							<element name="orders" type="string"
    								minOccurs="0" maxOccurs="1">
    							</element>
    							<element name="promotions" type="string"
    								minOccurs="0" maxOccurs="1">
    							</element>
    							<element name="policy" type="string"
    								minOccurs="0">
    							</element>
    						</sequence>
    					</complexType>
    				</element>
    			</sequence>
    		</complexType>
    	</element>
    	<element name="answerSource" type="string" minOccurs="0"
    		maxOccurs="1">
    	</element>
    	<element maxOccurs="1" minOccurs="0" name="answerGenerator">
    		<complexType>
    			<sequence>
    				<element maxOccurs="unbounded" minOccurs="0"
    					name="citedToolCalls" type="string" />
    				<element maxOccurs="1" minOccurs="0"
    					name="approvalStatus" type="string" />
    				<element maxOccurs="1" minOccurs="0"
    					name="confidence" type="string" />
    				<element maxOccurs="1" minOccurs="0" name="provider"
    					type="string" />
    				<element maxOccurs="1" minOccurs="0" name="model"
    					type="string" />
    				<element maxOccurs="1" minOccurs="0" name="warning"
    					type="string" />
    			</sequence>
    		</complexType>
    	</element>
    	<element name="rag" minOccurs="0" maxOccurs="1">
    		<complexType>
    			<sequence>
    				<element name="answerUsed" type="boolean" minOccurs="0" maxOccurs="1"></element>
    			</sequence>
    		</complexType></element>
    </sequence>
  </complexType>
  <element name="RouteSchemaElement" type="tns:RouteSchemaElementType"/>
</schema>
