<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/UploadSummary" xmlns:tns="http://www.example.org/UploadSummary" elementFormDefault="qualified">

    <complexType name="UploadSummaryType">
    	<sequence>
    		<element name="uploadId" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="fileName" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="status" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="documentCount" type="integer" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="productCount" type="integer" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="chunkCount" type="integer" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="errors" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="uploadedAt" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <element name="UploadSummary" type="tns:UploadSummaryType"></element>
</schema>