<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1779322135843" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1779322135843">
  <complexType name="UploadResponseElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="upload">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="uploadId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="fileName" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="status" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="documentCount" type="integer"/>
            <element maxOccurs="1" minOccurs="0" name="productCount" type="integer"/>
            <element maxOccurs="1" minOccurs="0" name="chunkCount" type="integer"/>
            <element maxOccurs="unbounded" minOccurs="0" name="errors" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="uploadedAt" type="string"/>
          </sequence>
        </complexType>
      </element>
      <element maxOccurs="1" minOccurs="0" name="status">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="dataset">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="products" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="inventory" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="customers" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="orders" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="policies" type="integer"/>
                </sequence>
              </complexType>
            </element>
            <element maxOccurs="1" minOccurs="0" name="ingestion">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="sourceCount" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="chunkCount" type="integer"/>
                  <element maxOccurs="1" minOccurs="0" name="embedding">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="provider" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="model" type="string"/>
                      </sequence>
                    </complexType>
                  </element>
                  <element maxOccurs="1" minOccurs="0" name="storage">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="provider" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="collection" type="string"/>
                      </sequence>
                    </complexType>
                  </element>
                  <element maxOccurs="unbounded" minOccurs="0" name="uploads">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="uploadId" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="fileName" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="status" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="documentCount" type="integer"/>
                        <element maxOccurs="1" minOccurs="0" name="productCount" type="integer"/>
                        <element maxOccurs="1" minOccurs="0" name="chunkCount" type="integer"/>
                        <element maxOccurs="unbounded" minOccurs="0" name="errors" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="uploadedAt" type="string"/>
                      </sequence>
                    </complexType>
                  </element>
                  <element maxOccurs="unbounded" minOccurs="0" name="sampleChunks">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="chunkId" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="documentId" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="title" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="documentType" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="tokenCount" type="integer"/>
                      </sequence>
                    </complexType>
                  </element>
                </sequence>
              </complexType>
            </element>
            <element maxOccurs="1" minOccurs="0" name="operations">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="provider" type="string"/>
                </sequence>
              </complexType>
            </element>
            <element maxOccurs="1" minOccurs="0" name="conversations">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="provider" type="string"/>
                </sequence>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="UploadResponseElement" type="tns:UploadResponseElementType"/>
</schema>
