<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1779154240456" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1779154240456">
  <complexType name="GetScenariosResponseElementType">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" name="scenarios">
        <complexType>
          <sequence>
            <element maxOccurs="1" minOccurs="0" name="id" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="title" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="goal" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="question" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="userId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="customerId" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="storeId" type="string"/>
            <element maxOccurs="unbounded" minOccurs="0" name="expected" type="string"/>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="GetScenariosResponseElement" type="tns:GetScenariosResponseElementType"/>
</schema>
