<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/AnswerSchema" xmlns:tns="http://www.example.org/AnswerSchema" elementFormDefault="qualified">

    <element name="answer" type="string"></element>

    <element name="answerSource" type="string"></element>

    <complexType name="AnswerResourceType">
    	<sequence>
    		<element name="answer" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="answerSource" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="citationsUsed" type="boolean" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="reasoningSummary" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="confidence" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <element name="AnswerResource" type="tns:AnswerResourceType"></element>
</schema>