<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.tibco.com/schemas/airliquide/cylinder"
           xmlns:tns="http://www.tibco.com/schemas/airliquide/cylinder"
           elementFormDefault="qualified">

    <xs:complexType name="CylinderType">
        <xs:sequence>
            <xs:element name="cylinderId" type="xs:string"/>
            <xs:element name="gasType" type="xs:string"/>
            <xs:element name="purityGrade" type="xs:string"/>
            <xs:element name="pressureBar" type="xs:integer"/>
            <xs:element name="volumeLiters" type="xs:integer"/>
            <xs:element name="location" type="xs:string"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="certExpiryDate" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Cylinder" type="tns:CylinderType"/>
    <xs:element name="Cylinders">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:Cylinder" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>