<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/InventorySchema" xmlns:tns="http://www.example.org/InventorySchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="InventoryList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Inventory" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="sku" minOccurs="0" maxOccurs="1"/>
              <xs:element type="xs:string" name="storeId" minOccurs="0" maxOccurs="1"/>
              <xs:element type="xs:string" name="productName" minOccurs="0" maxOccurs="1"/>
              <xs:element type="integer" name="quantity" minOccurs="0" maxOccurs="1"/>
              <xs:element type="xs:string" name="aisle" minOccurs="0" maxOccurs="1"/>
              <xs:element type="xs:string" name="status" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</schema>