<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1778535004886" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1778535004886">
  <complexType name="GetOrderReturnResponseElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="orderId" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="sku" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="productName" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="purchaseDate" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="ageDays" type="integer"/>
      <element maxOccurs="1" minOccurs="0" name="returnWindowDays" type="integer"/>
      <element maxOccurs="1" minOccurs="0" name="eligible" type="boolean"/>
      <element maxOccurs="1" minOccurs="0" name="loyaltyTier" type="string"/>
      <element maxOccurs="1" minOccurs="0" name="reason" type="string"/>
    </sequence>
  </complexType>
  <element name="GetOrderReturnResponseElement" type="tns:GetOrderReturnResponseElementType"/>
</schema>
